[env]
ANDROID_HOME = { value = "{{ tools['android-sdk'].path }}", tools = true }
_.path = { path = [
  "{{ tools['android-sdk'].path }}/cmdline-tools/{{ tools['android-sdk'].version }}/bin",
  "{{ tools['android-sdk'].path }}/platform-tools",
  "{{ tools['android-sdk'].path }}/emulator",
], tools = true }
