import type { AgentHookPluginFileInstallStrategy } from "../agent-hook-installer.js";

export const OPENCODE_V2_PLUGIN_SOURCE = [
  "// Paseo terminal activity hook for OpenCode v2 (opencode2).",
  "// Self-contained: the installed opencode2 binary cannot resolve",
  "// `@opencode-ai/plugin` from a standalone disk file, so this file defines a",
  "// minimal `Plugin.define` shim that returns the `{ id, setup(ctx) }`",
  "// definition the v2 plugin loader accepts. The same shape is what",
  "// `Plugin.define` produces, so the file stays compatible with opencode2",
  "// builds that do resolve `@opencode-ai/plugin`.",
  "const Plugin = {",
  "  define(definition) {",
  "    return definition;",
  "  },",
  "};",
  "",
  "const STATUS_EVENTS = {",
  '  busy: "session.status.busy",',
  '  retry: "session.status.retry",',
  '  idle: "session.status.idle",',
  "};",
  "",
  "// Translates public v2 bus events to paseo hook events. The v2 server reports",
  "// busy/idle through session.execution.started/succeeded (and session.status",
  "// when present); permission and form events map directly.",
  "function paseoEventFor(event) {",
  '  if (event?.type === "permission.asked") return "permission.asked";',
  '  if (event?.type === "permission.replied") return "permission.replied";',
  '  if (event?.type === "form.created") return "form.created";',
  '  if (event?.type === "form.replied") return "form.replied";',
  '  if (event?.type === "form.cancelled") return "form.cancelled";',
  '  if (event?.type === "session.idle") return "session.status.idle";',
  '  if (event?.type === "session.execution.started") return "session.status.busy";',
  '  if (event?.type === "session.execution.succeeded") return "session.status.idle";',
  '  if (event?.type === "session.step.started") return "session.status.busy";',
  '  if (event?.type !== "session.status") return null;',
  "  return STATUS_EVENTS[event?.data?.status?.type] ?? null;",
  "}",
  "",
  "function runPaseoHook(event) {",
  "  if (!process.env.PASEO_TERMINAL_ID) return;",
  "  try {",
  "    const child = Bun.spawn(",
  '      [process.env.PASEO_HOOK_CLI ?? "paseo", "hooks", "opencode-v2", event],',
  '      { stdin: "ignore", stdout: "ignore", stderr: "ignore" },',
  "    );",
  "    void child.exited.catch(() => {});",
  "  } catch {}",
  "}",
  "",
  "export default Plugin.define({",
  '  id: "paseo-terminal-activity",',
  "  setup(ctx) {",
  "    const subscribe = ctx.event?.subscribe;",
  '    if (typeof subscribe !== "function") return;',
  "    const events = subscribe.call(ctx.event);",
  "    void (async () => {",
  "      try {",
  "        for await (const event of events) {",
  "          const paseoEvent = paseoEventFor(event);",
  "          if (paseoEvent) runPaseoHook(paseoEvent);",
  "        }",
  "      } catch {}",
  "    })();",
  "  },",
  "});",
  "",
].join("\n");

export function createOpenCodeV2PluginInstallStrategy(): AgentHookPluginFileInstallStrategy {
  return {
    kind: "plugin-file",
    configDir: "opencode",
    configDirBase: "xdg-config",
    // Distinct from v1's paseo-terminal-activity.js: both providers share the
    // same opencode config dir, and the v1 and v2 plugin shapes are incompatible,
    // so each installs its own file and the v2 binary auto-discovers both.
    configFile: "plugins/paseo-terminal-activity-v2.js",
    configDirEnvOverride: "OPENCODE_CONFIG_DIR",
    hookMarker: "paseo hooks opencode-v2",
    source: OPENCODE_V2_PLUGIN_SOURCE,
  };
}
