#!/bin/bash
# setup-common.sh — shared setup logic for Junction dev environments
# Called by conductor-setup.sh, codex-setup.sh, and local.sh
#
# Expected env vars:
#   WORKSPACE_NAME  — sanitized workspace identifier (e.g. junction_local)
#   DAEMON_PORT     — port for Junction daemon (default: 6767)
#   API_PORT        — port for API server (default: 3100)
#   APP_PORT        — port for Vite app (default: 5173)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults
WORKSPACE_NAME="${WORKSPACE_NAME:-junction_local}"
DAEMON_PORT="${DAEMON_PORT:-6767}"
API_PORT="${API_PORT:-3100}"
APP_PORT="${APP_PORT:-5173}"

PG_HOST="localhost"
PG_PORT="5435"
PG_USER="postgres"
PG_PASS="postgres"
DATABASE_URL="postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${WORKSPACE_NAME}"

echo "══════════════════════════════════════════════════════"
echo "  Junction Setup"
echo "══════════════════════════════════════════════════════"
echo "  Workspace:  ${WORKSPACE_NAME}"
echo "  Database:   ${DATABASE_URL}"
echo "  Daemon:     http://localhost:${DAEMON_PORT}"
echo "  API:        http://localhost:${API_PORT}"
echo "  App:        http://localhost:${APP_PORT}"
echo "══════════════════════════════════════════════════════"

# ------------------------------------------------------------------
# 1. Start PostgreSQL container
# ------------------------------------------------------------------
echo ""
echo "→ Starting PostgreSQL on port ${PG_PORT}..."
docker compose -p junction -f "$REPO_ROOT/docker-compose.yml" up -d postgres

echo "→ Waiting for PostgreSQL to be ready..."
for i in $(seq 1 30); do
  if docker compose -p junction -f "$REPO_ROOT/docker-compose.yml" exec -T postgres pg_isready -U "$PG_USER" > /dev/null 2>&1; then
    echo "  PostgreSQL is ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  ERROR: PostgreSQL did not become ready in time."
    exit 1
  fi
  sleep 1
done

# ------------------------------------------------------------------
# 2. Create workspace-specific database (idempotent)
# ------------------------------------------------------------------
echo ""
echo "→ Creating database '${WORKSPACE_NAME}' (if not exists)..."
docker compose -p junction -f "$REPO_ROOT/docker-compose.yml" exec -T postgres \
  psql -U "$PG_USER" -d junction_dev -tc \
  "SELECT 1 FROM pg_database WHERE datname = '${WORKSPACE_NAME}'" \
  | grep -q 1 \
  || docker compose -p junction -f "$REPO_ROOT/docker-compose.yml" exec -T postgres \
    createdb -U "$PG_USER" "$WORKSPACE_NAME"
echo "  Database '${WORKSPACE_NAME}' ready."

# ------------------------------------------------------------------
# 3. Generate .env.local files
# ------------------------------------------------------------------
echo ""
echo "→ Generating environment files..."

# packages/api/.env.local
cat > "$REPO_ROOT/packages/api/.env.local" <<EOF
# Generated by setup-common.sh — do not commit
PORT=${API_PORT}
DATABASE_URL=${DATABASE_URL}
CORS_ORIGINS=http://localhost:${APP_PORT},http://127.0.0.1:${APP_PORT}
BETTER_AUTH_SECRET=junction-dev-secret-$(echo -n "$WORKSPACE_NAME" | md5 2>/dev/null || echo -n "$WORKSPACE_NAME" | md5sum 2>/dev/null | cut -d' ' -f1 || echo "default-dev-secret")
BETTER_AUTH_URL=http://localhost:${API_PORT}
EOF
echo "  packages/api/.env.local"

# packages/app/.env.local
cat > "$REPO_ROOT/packages/app/.env.local" <<EOF
# Generated by setup-common.sh — do not commit
VITE_API_URL=http://localhost:${API_PORT}
VITE_APP_PORT=${APP_PORT}
EOF
echo "  packages/app/.env.local"

# ------------------------------------------------------------------
# 4. Install dependencies
# ------------------------------------------------------------------
echo ""
echo "→ Installing dependencies..."
cd "$REPO_ROOT"
pnpm install

# ------------------------------------------------------------------
# 5. Build relay (required before daemon can start)
# ------------------------------------------------------------------
echo ""
echo "→ Building @junction/relay..."
pnpm --filter @junction/relay run build

# ------------------------------------------------------------------
# 6. Prisma generate + migrate
# ------------------------------------------------------------------
echo ""
echo "→ Running Prisma generate..."
cd "$REPO_ROOT/packages/api"
DATABASE_URL="$DATABASE_URL" pnpm exec prisma generate

echo "→ Pushing Prisma schema to database..."
DATABASE_URL="$DATABASE_URL" pnpm exec prisma db push

echo "→ Seeding dev user..."
DATABASE_URL="$DATABASE_URL" BETTER_AUTH_URL="http://localhost:${API_PORT}" BETTER_AUTH_SECRET="junction-dev-secret" pnpm run db:seed
cd "$REPO_ROOT"

# ------------------------------------------------------------------
# 7. Build server (required for CLI to work)
# ------------------------------------------------------------------
echo ""
echo "→ Building @junction/server..."
NODE_OPTIONS="--max-old-space-size=4096" pnpm --filter @junction/server run build

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Setup complete!"
echo "══════════════════════════════════════════════════════"
