import { StyleSheet } from "react-native-unistyles";

export const elementContextPanelStyles = StyleSheet.create((theme) => ({
  overlay: {
    position: "absolute",
    zIndex: 1,
    padding: theme.spacing[3],
    alignItems: "center",
    justifyContent: "flex-end",
  },
  panel: {
    width: "100%",
    maxWidth: 345,
    maxHeight: 360,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface0,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
  },
  compactPanel: {
    width: "100%",
    maxWidth: 300,
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[1],
    paddingHorizontal: theme.spacing[1],
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface0,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  compactIconButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: theme.colors.surface1,
  },
  compactCommentInput: {
    flex: 1,
    minWidth: 0,
    height: 36,
    paddingHorizontal: theme.spacing[1],
    fontSize: theme.fontSize.sm,
    color: theme.colors.foreground,
  },
  compactSubmit: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: theme.colors.accent,
  },
  compactSubmitDisabled: { opacity: 0.4 },
  toolbarButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.borderRadius.md,
  },
  headerText: { flex: 1, minWidth: 0 },
  title: { fontSize: theme.fontSize.sm, fontWeight: "600", color: theme.colors.foreground },
  targetBlock: {
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[1],
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  targetHeader: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing[2],
  },
  elementText: {
    fontSize: theme.fontSize.sm,
    lineHeight: 18,
    color: theme.colors.foregroundMuted,
  },
  expandedCommentInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 36,
    paddingHorizontal: theme.spacing[1],
    fontSize: theme.fontSize.sm,
    color: theme.colors.foreground,
  },
  actions: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing[1],
    paddingHorizontal: theme.spacing[2],
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  panelSubmit: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: theme.colors.accent,
  },
}));
