export const providerAccountCopy = {
  title: "Provider accounts",
  description:
    "Keep separate Codex and Claude sign-ins on this host. New agents stay pinned to the account they start with.",
  add: "Add account",
  addTitle: "Add provider account",
  editTitle: "Rename provider account",
  provider: "Provider",
  name: "Account name",
  namePlaceholder: "Work",
  create: "Create account",
  save: "Save",
  saving: "Saving…",
  system: "System account",
  systemHint: "Uses the sign-in already configured for this host.",
  account: "Account",
  hostDefault: "Host default",
  hostDefaultWithAccount: (name: string) => `Host default (${name})`,
  unavailableAccount: "Unavailable account",
  noAccounts: "No accounts are configured for this provider.",
  default: "Default",
  makeDefault: "Make default",
  signedIn: "Signed in",
  notSignedIn: "Not signed in",
  signIn: "Sign in",
  signInAgain: "Sign in again",
  signInTitle: (name: string) => `Sign in to ${name}`,
  signInStarting: "Starting a secure provider sign-in…",
  signInWaiting: "Finish signing in in your browser. This window updates automatically.",
  signInOnHost:
    "The provider opened its sign-in flow on the host. Complete it there; this window updates automatically.",
  deviceCode: "One-time code",
  copyCode: "Copy code",
  openBrowser: "Open browser",
  cancelSignIn: "Cancel sign-in",
  signInComplete: "Account connected",
  signInCompleteHint: "New agents can now use this account profile.",
  signInFailed: "Sign-in failed",
  close: "Close",
  edit: "Rename",
  remove: "Remove",
  removeTitle: "Remove account?",
  removeMessage: (name: string) =>
    `Remove “${name}”? Existing agents pinned to it must be archived first.`,
  loading: "Loading provider accounts…",
  unavailable: "Connect to this host to manage provider accounts.",
  upgradeRequired: "Update this host to manage multiple provider accounts.",
  errorTitle: "Unable to load provider accounts",
  retry: "Retry",
  duplicateHint: "Names must be unique within each provider.",
  providers: {
    codex: "Codex",
    claude: "Claude",
  },
} as const;
